import { StandardColumnModel, StandardColumnType } from '../../shares/interfaces'

export const importSalaryColumns = (): StandardColumnModel[] => {
    return [
        {
            id: 1,
            name: 'index',
            fixedColumn: true,
            fixedRight: false,
            attr: 'STT',
            type: StandardColumnType.TEXT,
            width: '50px',
            isRequire: false,
            isFilter: false,
            isSort: false,
            indexColumn: true,
            classes: 'text-center',
        },
        {
            id: 2,
            name: 'month',
            fixedColumn: false,
            fixedRight: false,
            attr: 'Tháng',
            type: StandardColumnType.TEXT,
            width: '100px',
            isRequire: true,
            filter: { type: 14, options: [] },
            isSort: true,
            classes: 'text-center',
        },
        {
            id: 3,
            name: 'fileName',
            fixedColumn: false,
            fixedRight: false,
            attr: 'File đính kèm',
            type: StandardColumnType.TEXT,
            width: '150px',
            isRequire: true,
            filter: { type: 0, options: [] },
            isSort: true,
            classes: 'text-center',
        },
        {
            id: 4,
            name: 'createdByName',
            fixedColumn: false,
            fixedRight: false,
            attr: 'Người tạo',
            type: StandardColumnType.TEXT,
            width: '120px',
            isRequire: true,
            filter: { type: 8, options: [] },
            isSort: true,
            classes: 'text-center',
        },
        {
            id: 5,
            name: 'createdAt',
            fixedColumn: false,
            fixedRight: false,
            attr: 'Ngày tạo',
            type: StandardColumnType.TEXT,
            width: '120px',
            isRequire: true,
            filter: { type: 8, options: [] },
            isSort: true,
            classes: 'text-center',
        },
    ];
}
