import { StandardColumnModel, StandardColumnType, ActionConfig } from '../../shares/interfaces';
import { IconHtml } from '../../shares/enum/icon-html.enum';

export const overTimeManageColumns = (): StandardColumnModel[] => [
    {
      id: 0,
      name: 'index',
      fixedColumn: true,
      fixedRight: false,
      attr: 'STT',
      type: StandardColumnType.TEXT,
      width: '50px',
      isRequire: false,
      isSort: false,
      indexColumn: true,
      classes: 'text-center'
    },

        {
      id: 10,
      name: 'response_action',
      fixedColumn: false,
      fixedRight: true,
      attr: 'Thao tác',
      type: StandardColumnType.ACTION,
      width: '100px',
      isFilter: false,
      isSort: false,
      classes: 'text-center',
      listAction: [
        {
            key: 'approve',
            icon: 'check',
            label: 'Chấp thuận',
            html: IconHtml.ACCEPT,
            fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
        {
            key: 'reject',
            icon: 'close',
            label: 'Từ chối',
            html: IconHtml.REJECT,
            fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
      ],
    },
    {
      id: 2,
      name: 'employeeCode',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Mã nhân viên',
      type: StandardColumnType.TEXT,
      width: '120px',
      isRequire: true,
      isFilter: true,
      filter: {
        type: StandardColumnType.INPUT,
      },
      isSort: true,
    },
    {
      id: 3,
      name: 'employeeName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Tên nhân viên',
      type: StandardColumnType.TEXT,
      width: '180px',
      isRequire: true,
      isFilter: true,
      filter: {
        type: StandardColumnType.INPUT,
      },
      isSort: true,
    },
    {
      id: 4,
      name: 'otDate', // Guessing field name
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày đăng ký',
      type: StandardColumnType.TEXT,
      width: '150px',
      isRequire: true,
      isFilter: true,
      filter: {
        type: StandardColumnType.DATE_PICKER,
      },
      isSort: true,
    },
    {
        id: 5,
        name: 'startTime',
        fixedColumn: false,
        fixedRight: false,
        attr: 'Bắt đầu',
        type: StandardColumnType.TEXT,
        width: '120px',
        isRequire: true,
        isFilter: true,
        filter: {
          type: StandardColumnType.INPUT,
        },
        isSort: true,
    },
    {
        id: 6,
        name: 'endTime',
        fixedColumn: false,
        fixedRight: false,
        attr: 'Kết thúc',
        type: StandardColumnType.TEXT,
        width: '120px',
        isRequire: true,
        isFilter: true,
        filter: {
            type: StandardColumnType.INPUT,
        },
        isSort: true,
    },
    {
        id: 7,
        name: 'totalHour',
        fixedColumn: false,
        fixedRight: false,
        attr: 'Tổng giờ',
        type: StandardColumnType.TEXT,
        width: '100px',
        isRequire: true,
        isFilter: true,
        filter: {
            type: StandardColumnType.INPUT,
        },
        isSort: true,
    },
    {
        id: 8,
        name: 'reason',
        fixedColumn: false,
        fixedRight: false,
        attr: 'Lý do',
        type: StandardColumnType.TEXT,
        width: '200px',
        isRequire: true,
        isFilter: true,
        filter: {
            type: StandardColumnType.INPUT,
        },
        isSort: true,
    },
    {
        id: 9,
        name: 'status',
        fixedColumn: false,
        fixedRight: false,
        attr: 'Trạng thái',
        type: StandardColumnType.TEXT,
        width: '150px',
        isRequire: true,
        isFilter: true,
        filter: {
          type: StandardColumnType.SELECT,
          options: [
            { value: 'ACCEPTED', label: 'Đã duyệt' },
            { value: 'PENDING', label: 'Chờ duyệt' },
            { value: 'REJECTED', label: 'Từ chối' },
          ]
        },
        isSort: true,
      },
  ];
