import { StandardColumnModel, StandardColumnType } from '../../shares/interfaces';

export const importAttendanceColumns = (): StandardColumnModel[] => {
  return [
    {
      id: 1,
      name: 'index',
      fixedColumn: true,
      fixedRight: false,
      attr: 'STT',
      type: StandardColumnType.TEXT,
      width: '50px',
      isRequire: false,
      isFilter: false,
      isSort: false,
      indexColumn: true,
    },
    {
      id: 2,
      name: 'month',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Tháng',
      type: StandardColumnType.TEXT,
      width: '100px',
      isRequire: true,
      filter: { type: 14, options: [] },
      isSort: true,
    },
    {
      id: 3,
      name: 'fileAttachment',
      fixedColumn: false,
      fixedRight: false,
      attr: 'File đính kèm',
      type: StandardColumnType.TEXT,
      width: '150px',
      isRequire: true,
      filter: { type: 0, options: [] },
      isSort: true,
    },
    {
      id: 4,
      name: 'creator',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Người tạo',
      type: StandardColumnType.TEXT,
      width: '120px',
      isRequire: true,
      filter: { type: 8, options: [] },
      isSort: true,
    },
    {
      id: 5,
      name: 'createdDate',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày tạo',
      type: StandardColumnType.TEXT,
      width: '120px',
      isRequire: true,
      filter: { type: 8, options: [] },
      isSort: true,
    },
  ];
}
