import { ActionConfig, RequestStatus, StandardColumnModel, StandardColumnType } from '../../shares/interfaces';
import { IconHtml } from '../../shares/enum/icon-html.enum';
export const specialScheduleColumns = (): StandardColumnModel[] => {
  return [
    {
      id: 1,
      name: 'index',
      fixedColumn: true,
      fixedRight: false,
      attr: 'STT',
      type: StandardColumnType.TEXT,
      width: '50px',
      isRequire: false,
      isFilter: false,
      isSort: false,
      indexColumn: true,
    },
    {
      id: 2,
      name: 'action',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Thao tác',
      type: StandardColumnType.ACTION,
      width: '80px',
      isFilter: false,
      isSort: false,
      rulesAction: {
        isEdit: [''],
        isRemove: [''],
      },
      listAction: [
        {
          key: 'approve',
          icon: 'approve',
          label: 'Duyệt',
          html: IconHtml.ACCEPT,
          // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_APPROVAL'],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
        {
          key: 'reject',
          icon: 'reject',
          label: 'Từ chối',
          html: IconHtml.REJECT,
          // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_APPROVAL'],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
      ],
    },
    {
      id: 3,
      name: 'employeeUserName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Mã nhân viên',
      type: StandardColumnType.TEXT,
      width: '130px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
      classes: 'text-right',
    },
    {
      id: 4,
      name: 'employeeName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Tên nhân viên',
      type: StandardColumnType.TEXT,
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 5,
      name: 'absenceStatus',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Trạng thái',
      type: StandardColumnType.TAG,
      isFilter: true,
      width: '130px',
      filter: {
        name: 'absenceStatus',
        type: StandardColumnType.SELECT,
        options: RequestStatus, // Sử dụng RequestStatus đã định nghĩa lại
        multiple: true,
      },
      isSort: true,
      classes: 'tag-left',
    },
    {
      id: 6,
      name: 'employeeEmail',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Email',
      type: StandardColumnType.TEXT,
      width: '130px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 7,
      name: 'organizationName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Phòng ban',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'organizationId',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 8,
      name: 'absenceTypeName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Loại',
      type: StandardColumnType.SELECT,
      width: '130px',
      isRequire: false,
      isFilter: true,
      filter: {
        type: StandardColumnType.SELECT,
        name: 'absenceTypeCode',
        // selectOptionsType: EnumSelectOptionType.leaveType, // BỎ
        multiple: true,
      },
    },
    {
      id: 9,
      name: 'startDate',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày yêu cầu',
      type: StandardColumnType.DATE_RANGE_PICKER,
      width: '140px',
      isSort: true,
      isFilter: true,
    },
    {
      id: 10,
      name: 'timeRegisterStart',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Giờ đăng ký (từ)',
      type: StandardColumnType.TIME_RANGE_PICKER,
      width: '150px',
      isFilter: true,
      isSort: true,
      classes: 'text-center',
    },
    {
      id: 11,
      name: 'timeRegisterEnd',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Giờ đăng ký (đến)',
      type: StandardColumnType.TIME_RANGE_PICKER,
      width: '150px',
      isFilter: true,
      isSort: true,
      classes: 'text-center',
    },
    {
      id: 12,
      name: 'absenceReason',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Lý do',
      type: StandardColumnType.TEXT,
      width: '160px',
      isRequire: true,
      isFilter: true,
    },
  ];

}
