import {
  ActionConfig,
  RequestStatus,
  StandardColumnModel,
  StandardColumnType,
  StandardFormItemModel
} from '../../shares/interfaces';
import { IconHtml } from '../../shares/enum/icon-html.enum';
export const specialScheduleColumns = (): StandardColumnModel[] => {
  return [
    {
      id: 0,
      name: 'index',
      fixedColumn: true,
      fixedRight: false,
      attr: 'STT',
      type: StandardColumnType.TEXT,
      width: '50px',
      isRequire: false,
      isFilter: false,
      isSort: false,
      indexColumn: true,
    },
    {
      id: 1,
      name: 'action',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Thao tác',
      type: StandardColumnType.ACTION,
      width: '100px',
      isFilter: false,
      isSort: false,
      listAction: [
        {
          key: 'edit',
          icon: 'edit',
          label: 'Sửa',
          html: IconHtml.UPDATE,
          // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_UPDATE'],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
        {
          key: 'delete',
          icon: 'delete',
          label: 'Xóa',
          html: IconHtml.DELETE,
          // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_DELETE'],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
        // {
        //   key: 'approve',
        //   icon: 'approve',
        //   label: 'Duyệt',
        //   html: IconHtml.ACCEPT,
        //   // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_APPROVAL'],
        //   fieldCheckShow: 'isActiveAction',
        // } as ActionConfig,
        // {
        //   key: 'reject',
        //   icon: 'reject',
        //   label: 'Từ chối',
        //   html: IconHtml.REJECT,
        //   // rules: ['ROLE_ADMIN_SYSTEM', 'ROLE_ABSENCE_APPROVAL'],
        //   fieldCheckShow: 'isActiveAction',
        // } as ActionConfig,
      ],
    },
    {
      id: 2,
      name: 'employeeCode',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Mã NV',
      type: StandardColumnType.TEXT,
      width: '100px',
      isFilter: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 3,
      name: 'employeeName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Tên NV',
      type: StandardColumnType.TEXT,
      width: '150px',
      isFilter: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 4,
      name: 'departmentName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Phòng ban',
      type: StandardColumnType.TEXT,
      width: '120px',
      isFilter: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 5,
      name: 'startDate',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày bắt đầu',
      type: StandardColumnType.DATE_PICKER,
      width: '120px',
      isFilter: true,
      filter: { type: StandardColumnType.DATE_PICKER },
    },
    {
      id: 6,
      name: 'endDate',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày kết thúc',
      type: StandardColumnType.DATE_PICKER,
      width: '120px',
      isFilter: true,
      filter: { type: StandardColumnType.DATE_PICKER },
    },
    {
      id: 7,
      name: 'morningStart',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Sáng từ',
      type: StandardColumnType.TEXT,
      width: '90px',
      isFilter: false,
    },
    {
      id: 8,
      name: 'morningEnd',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Sáng đến',
      type: StandardColumnType.TEXT,
      width: '90px',
      isFilter: false,
    },
    {
      id: 9,
      name: 'afternoonStart',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Chiều từ',
      type: StandardColumnType.TEXT,
      width: '90px',
      isFilter: false,
    },
    {
      id: 10,
      name: 'afternoonEnd',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Chiều đến',
      type: StandardColumnType.TEXT,
      width: '90px',
      isFilter: false,
    },
    {
      id: 11,
      name: 'type',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Loại',
      type: StandardColumnType.SELECT,
      width: '100px',
      isFilter: true,
      filter: {
        type: StandardColumnType.SELECT,
        options: [
          { value: 'ON_SITE', label: 'On Site' },
          { value: 'MATERNITY', label: 'MATERNITY' },
        ],
      },
    },
    {
      id: 12,
      name: 'reason',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Lý do',
      type: StandardColumnType.TEXT,
      width: '180px',
      isFilter: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 13,
      name: 'status',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Trạng thái',
      type: StandardColumnType.SELECT,
      width: '110px',
      isFilter: true,
      filter: {
        type: StandardColumnType.SELECT,
        options: [
          { value: 'PENDING', label: 'Chờ duyệt' },
          { value: 'APPROVED', label: 'Đã duyệt' },
          { value: 'REJECTED', label: 'Từ chối' },
        ],
      },
    },
  ];

}

export const specialScheduleColumnFilter: StandardFormItemModel[] = [
  {
    field: 'employeeId',
    label: 'Mã nhân viên',
    type: StandardColumnType.INPUT_NUMBER,
  },
  {
    field: 'employeeName',
    label: 'Tên nhân viên',
    type: StandardColumnType.TEXT,
  },
  {
    field: 'employeeEmail',
    label: 'Email',
    type: StandardColumnType.TEXT,
  },
  {
    field: 'departmentName',
    label: 'Phòng ban',
    type: StandardColumnType.SELECT,
    multiple: false,
    options: [],
  },
  {
    field: 'absenceTypeCode',
    label: 'Loại',
    type: StandardColumnType.SELECT,
    options: [],
    multiple: false,
  },
  {
    field: 'absenceReason',
    label: 'Lý do',
    type: StandardColumnType.TEXT,
  },
];
