import { RequestStatus, StandardColumnModel, StandardColumnType } from '../shares/interfaces';


export const employeeManageColumns = ():StandardColumnModel[] => {
  return [
    // {
    //   id: 2,
    //   name: 'action',
    //   fixedColumn: true,
    //   fixedRight: false,
    //   attr: 'Thao tác',
    //   type: StandardColumnType.ACTION,
    //   width: '80px',
    //   isFilter: false,
    //   isSort: false,
    // },
    {
      id: 3,
      name: 'employeeUserName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Mã nhân viên',
      type: StandardColumnType.TEXT,
      width: '130px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
      classes: 'text-right',
    },
    {
      id: 4,
      name: 'employeeName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Tên nhân viên',
      type: StandardColumnType.TEXT,
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 5,
      name: 'absenceStatus',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Trạng thái',
      type: StandardColumnType.TAG,
      isFilter: true,
      width: '130px',
      filter: {
        name: 'absenceStatus',
        type: StandardColumnType.SELECT,
        options: RequestStatus,
        multiple: true,
      },
      isSort: true,
      classes: 'tag-left',
    },
    {
      id: 6,
      name: 'employeeEmail',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Email',
      type: StandardColumnType.TEXT,
      width: '130px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 7,
      name: 'organizationName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Phòng ban',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'organizationId',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 8,
      name: 'positionName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Chức danh',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 9,
      name: 'staffRole',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Role',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'roleId',
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 10,
      name: 'workPositionName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Vị trí công việc',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'jobPositionId',
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 11,
      name: 'levelName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Level',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'levelId',
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 12,
      name: 'statusName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Tình trạng',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 13,
      name: 'isActive',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Trạng thái',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 13,
      name: 'gender',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Giới tính',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 14,
      name: 'birthDay',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày sinh',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 13,
      name: 'phoneNumber',
      fixedColumn: false,
      fixedRight: false,
      attr: 'SĐT',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 17,
      name: 'entryDate',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày vào làm',
      type: StandardColumnType.DATE_RANGE_PICKER,
      width: '140px',
      isSort: true,
      isFilter: true,
    },
    {
      id: 18,
      name: 'createdUser',
      fixedColumn: false,
      attr: 'Người tạo',
      type: StandardColumnType.TEXT,
      isSort: false,
      isFilter: true,
      width: '250px',
    },
  ];
};
