import {
  ActionConfig,
  RequestStatus,
  StandardColumnModel,
  StandardColumnType,
  StandardFormItemModel
} from '../shares/interfaces';
import { IconHtml } from '../shares/enum/icon-html.enum';


export const employeeManageColumns = ():StandardColumnModel[] => {
  return [
    {
      id: 1,
      name: 'index',
      fixedColumn: true,
      fixedRight: false,
      attr: 'STT',
      type: StandardColumnType.TEXT,
      width: '60px',
      isFilter: false,
      isSort: false,
    },
    {
      id: 2,
      name: 'action',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Thao tác',
      type: StandardColumnType.ACTION,
      width: '100px',
      isFilter: false,
      isSort: false,
      rulesAction: {
        isEdit: [''],
        isRemove: [''],
      },
      listAction: [
        {
          key: 'edit',
          icon: 'edit',
          label: 'Chỉnh sửa',
          html: IconHtml.UPDATE,
          rules: [],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
        {
          key: 'delete',
          icon: 'delete',
          label: 'Xóa',
          html: IconHtml.DELETE,
          rules: [],
          fieldCheckShow: 'isActiveAction',
        } as ActionConfig,
      ],
    },
    {
      id: 3,
      name: 'code',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Mã nhân viên',
      type: StandardColumnType.TEXT,
      width: '100px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
      classes: 'text-right',
    },
    {
      id: 4,
      name: 'fullName',
      fixedColumn: true,
      fixedRight: false,
      attr: 'Tên nhân viên',
      type: StandardColumnType.TEXT,
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    // {
    //   id: 5,
    //   name: 'absenceStatus',
    //   fixedColumn: true,
    //   fixedRight: false,
    //   attr: 'Trạng thái',
    //   type: StandardColumnType.TAG,
    //   isFilter: true,
    //   width: '130px',
    //   filter: {
    //     name: 'absenceStatus',
    //     type: StandardColumnType.SELECT,
    //     options: RequestStatus,
    //     multiple: true,
    //   },
    //   isSort: true,
    //   classes: 'tag-left',
    // },
    {
      id: 6,
      name: 'email',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Email',
      type: StandardColumnType.TEXT,
      width: '200px',
      isFilter: true,
      isSort: true,
      filter: { type: StandardColumnType.INPUT },
    },
    {
      id: 7,
      name: 'departmentName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Phòng ban',
      width: '150px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'organizationId',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 8,
      name: 'positionName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Chức danh',
      width: '120px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 10,
      name: 'position',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Vị trí công việc',
      width: '120px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'jobPositionId',
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 11,
      name: 'levelName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Level',
      width: '100px',
      isFilter: true,
      isSort: true,
      filter: {
        name: 'levelId',
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 12,
      name: 'statusName',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Tình trạng',
      width: '100px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    // {
    //   id: 13,
    //   name: 'isActive',
    //   fixedColumn: false,
    //   fixedRight: false,
    //   attr: 'Trạng thái',
    //   width: '150px',
    //   isFilter: true,
    //   isSort: true,
    //   filter: {
    //     name: '',
    //     // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
    //     multiple: true,
    //   },
    //   type: StandardColumnType.SELECT,
    // },
    {
      id: 13,
      name: 'gender',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Giới tính',
      width: '50px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 14,
      name: 'dateOfBirth',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày sinh',
      width: '100px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 13,
      name: 'phoneNumber',
      fixedColumn: false,
      fixedRight: false,
      attr: 'SĐT',
      width: '100px',
      isFilter: true,
      isSort: true,
      filter: {
        name: '',
        // selectOptionsType: EnumSelectOptionType.organizationProfile, // BỎ
        multiple: true,
      },
      type: StandardColumnType.SELECT,
    },
    {
      id: 17,
      name: 'createdAt',
      fixedColumn: false,
      fixedRight: false,
      attr: 'Ngày vào làm',
      type: StandardColumnType.DATE_RANGE_PICKER,
      width: '140px',
      isSort: true,
      isFilter: true,
    },
  ];
};
export const employeeColumnFilter: StandardFormItemModel[] = [

]
